/**
 * @file cy_eru_map.h
 *
 * @cond
 *****************************************************************************
 * \copyright
 * (c) 2016-2026, Infineon Technologies AG or an affiliate of
 * Infineon Technologies AG.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *****************************************************************************
 * @endcond
 */

#ifndef CY_ERU_MAP_H
#define CY_ERU_MAP_H

/*********************************************************************************************************************
 * MACROS
 *********************************************************************************************************************/
#define ERU0_ETL0 CY_ERU0, 0
#define ERU0_ETL1 CY_ERU0, 1
#define ERU0_ETL2 CY_ERU0, 2
#define ERU0_ETL3 CY_ERU0, 3

#define ERU0_OGU0 CY_ERU0, 0
#define ERU0_OGU1 CY_ERU0, 1
#define ERU0_OGU2 CY_ERU0, 2
#define ERU0_OGU3 CY_ERU0, 3

#if defined(ERU1)
#define ERU1_ETL0 CY_ERU1, 0
#define ERU1_ETL1 CY_ERU1, 1
#define ERU1_ETL2 CY_ERU1, 2
#define ERU1_ETL3 CY_ERU1, 3

#define ERU1_OGU0 CY_ERU1, 0
#define ERU1_OGU1 CY_ERU1, 1
#define ERU1_OGU2 CY_ERU1, 2
#define ERU1_OGU3 CY_ERU1, 3
#endif


#if (CY_DEVICE_ID == CY_DEVICE_PSC1M2) && (CY_DEVICE_PACKAGE == VQFN40)
#define ERU0_ETL0_INPUTA_ACMP0_OUT          CY_ERU_ETL_INPUT_A0
#define ERU0_ETL0_INPUTA_ACMP2_OUT          CY_ERU_ETL_INPUT_A2
#define ERU0_ETL0_INPUTA_P2_4               CY_ERU_ETL_INPUT_A1
#define ERU0_ETL0_INPUTA_VADC0_G0BFLOUT0    CY_ERU_ETL_INPUT_A3
#define ERU0_ETL0_INPUTB_ACMP0_OUT          CY_ERU_ETL_INPUT_B2
#define ERU0_ETL0_INPUTB_P2_0               CY_ERU_ETL_INPUT_B0
#define ERU0_ETL0_INPUTB_P2_2               CY_ERU_ETL_INPUT_B1
#define ERU0_ETL0_INPUTB_VADC0_G1BFLOUT0    CY_ERU_ETL_INPUT_B3
#define ERU0_ETL1_INPUTA_ACMP1_OUT          CY_ERU_ETL_INPUT_A0
#define ERU0_ETL1_INPUTA_ACMP3_OUT          CY_ERU_ETL_INPUT_A2
#define ERU0_ETL1_INPUTA_P2_5               CY_ERU_ETL_INPUT_A1
#define ERU0_ETL1_INPUTA_VADC0_G0BFLOUT1    CY_ERU_ETL_INPUT_A3
#define ERU0_ETL1_INPUTB_ACMP1_OUT          CY_ERU_ETL_INPUT_B2
#define ERU0_ETL1_INPUTB_P2_1               CY_ERU_ETL_INPUT_B0
#define ERU0_ETL1_INPUTB_P2_3               CY_ERU_ETL_INPUT_B1
#define ERU0_ETL1_INPUTB_VADC0_G1BFLOUT1    CY_ERU_ETL_INPUT_B3
#define ERU0_ETL2_INPUTA_ACMP2_OUT          CY_ERU_ETL_INPUT_A0
#define ERU0_ETL2_INPUTA_ACMP4_OUT          CY_ERU_ETL_INPUT_A2
#define ERU0_ETL2_INPUTA_P2_6               CY_ERU_ETL_INPUT_A1
#define ERU0_ETL2_INPUTA_VADC0_G0BFLOUT2    CY_ERU_ETL_INPUT_A3
#define ERU0_ETL2_INPUTB_ACMP2_OUT          CY_ERU_ETL_INPUT_B2
#define ERU0_ETL2_INPUTB_P2_10              CY_ERU_ETL_INPUT_B0
#define ERU0_ETL2_INPUTB_P2_11              CY_ERU_ETL_INPUT_B1
#define ERU0_ETL2_INPUTB_VADC0_G1BFLOUT2    CY_ERU_ETL_INPUT_B3
#define ERU0_ETL3_INPUTA_ACMP5_OUT          CY_ERU_ETL_INPUT_A2
#define ERU0_ETL3_INPUTA_ACMP7_OUT          CY_ERU_ETL_INPUT_A0
#define ERU0_ETL3_INPUTA_P2_7               CY_ERU_ETL_INPUT_A1
#define ERU0_ETL3_INPUTA_VADC0_G0BFLOUT3    CY_ERU_ETL_INPUT_A3
#define ERU0_ETL3_INPUTB_ACMP6_OUT          CY_ERU_ETL_INPUT_B2
#define ERU0_ETL3_INPUTB_P2_8               CY_ERU_ETL_INPUT_B1
#define ERU0_ETL3_INPUTB_P2_9               CY_ERU_ETL_INPUT_B0
#define ERU0_ETL3_INPUTB_VADC0_G1BFLOUT3    CY_ERU_ETL_INPUT_B3
#define ERU1_ETL0_INPUTA_ACMP1_OUT          CY_ERU_ETL_INPUT_A0
#define ERU1_ETL0_INPUTB_CCU40_ST0          CY_ERU_ETL_INPUT_B0
#define ERU1_ETL0_INPUTB_CCU41_ST0          CY_ERU_ETL_INPUT_B1
#define ERU1_ETL0_INPUTB_CCU80_ST0          CY_ERU_ETL_INPUT_B2
#define ERU1_ETL0_INPUTB_CCU81_ST0          CY_ERU_ETL_INPUT_B3
#define ERU1_ETL1_INPUTB_CCU40_ST1          CY_ERU_ETL_INPUT_B0
#define ERU1_ETL1_INPUTB_CCU41_ST1          CY_ERU_ETL_INPUT_B1
#define ERU1_ETL1_INPUTB_CCU80_ST3          CY_ERU_ETL_INPUT_B2
#define ERU1_ETL1_INPUTB_CCU81_ST3          CY_ERU_ETL_INPUT_B3
#define ERU1_ETL2_INPUTA_ACMP2_OUT          CY_ERU_ETL_INPUT_A0
#define ERU1_ETL2_INPUTB_CCU40_ST2          CY_ERU_ETL_INPUT_B0
#define ERU1_ETL2_INPUTB_CCU41_ST2          CY_ERU_ETL_INPUT_B1
#define ERU1_ETL2_INPUTB_CCU80_ST1          CY_ERU_ETL_INPUT_B2
#define ERU1_ETL2_INPUTB_CCU81_ST1          CY_ERU_ETL_INPUT_B3
#define ERU1_ETL3_INPUTA_ACMP0_OUT          CY_ERU_ETL_INPUT_A0
#define ERU1_ETL3_INPUTB_CCU40_ST3          CY_ERU_ETL_INPUT_B0
#define ERU1_ETL3_INPUTB_CCU41_ST3          CY_ERU_ETL_INPUT_B1
#define ERU1_ETL3_INPUTB_CCU80_ST2          CY_ERU_ETL_INPUT_B2
#define ERU1_ETL3_INPUTB_CCU81_ST2          CY_ERU_ETL_INPUT_B3

#define ERU0_OGU0_PERIPHERAL_TRIGGER_CCU40_SR0  CY_ERU_OGU_PERIPHERAL_TRIGGER1
#define ERU0_OGU0_PERIPHERAL_TRIGGER_CCU80_SR2  CY_ERU_OGU_PERIPHERAL_TRIGGER3
#define ERU0_OGU0_PERIPHERAL_TRIGGER_VADC_C0SR2 CY_ERU_OGU_PERIPHERAL_TRIGGER2
#define ERU0_OGU1_PERIPHERAL_TRIGGER_CCU40_SR1  CY_ERU_OGU_PERIPHERAL_TRIGGER1
#define ERU0_OGU1_PERIPHERAL_TRIGGER_CCU80_SR2  CY_ERU_OGU_PERIPHERAL_TRIGGER3
#define ERU0_OGU1_PERIPHERAL_TRIGGER_VADC_C0SR2 CY_ERU_OGU_PERIPHERAL_TRIGGER2
#define ERU0_OGU2_PERIPHERAL_TRIGGER_CCU40_SR2  CY_ERU_OGU_PERIPHERAL_TRIGGER1
#define ERU0_OGU2_PERIPHERAL_TRIGGER_CCU80_SR3  CY_ERU_OGU_PERIPHERAL_TRIGGER3
#define ERU0_OGU2_PERIPHERAL_TRIGGER_VADC_C0SR3 CY_ERU_OGU_PERIPHERAL_TRIGGER2
#define ERU0_OGU3_PERIPHERAL_TRIGGER_CCU40_SR3  CY_ERU_OGU_PERIPHERAL_TRIGGER1
#define ERU0_OGU3_PERIPHERAL_TRIGGER_CCU80_SR3  CY_ERU_OGU_PERIPHERAL_TRIGGER3
#define ERU0_OGU3_PERIPHERAL_TRIGGER_VADC_C0SR3 CY_ERU_OGU_PERIPHERAL_TRIGGER2
#define ERU1_OGU0_PERIPHERAL_TRIGGER_CCU41_SR0  CY_ERU_OGU_PERIPHERAL_TRIGGER1
#define ERU1_OGU0_PERIPHERAL_TRIGGER_CCU81_SR2  CY_ERU_OGU_PERIPHERAL_TRIGGER3
#define ERU1_OGU1_PERIPHERAL_TRIGGER_CCU41_SR1  CY_ERU_OGU_PERIPHERAL_TRIGGER1
#define ERU1_OGU1_PERIPHERAL_TRIGGER_CCU81_SR2  CY_ERU_OGU_PERIPHERAL_TRIGGER3
#define ERU1_OGU2_PERIPHERAL_TRIGGER_CCU41_SR2  CY_ERU_OGU_PERIPHERAL_TRIGGER1
#define ERU1_OGU2_PERIPHERAL_TRIGGER_CCU81_SR3  CY_ERU_OGU_PERIPHERAL_TRIGGER3
#define ERU1_OGU3_PERIPHERAL_TRIGGER_CCU41_SR3  CY_ERU_OGU_PERIPHERAL_TRIGGER1
#define ERU1_OGU3_PERIPHERAL_TRIGGER_CCU81_SR3  CY_ERU_OGU_PERIPHERAL_TRIGGER3
#endif


#if (CY_DEVICE_ID == CY_DEVICE_PSC1M2) && (CY_DEVICE_PACKAGE == VQFN48)
#define ERU0_ETL0_INPUTA_ACMP0_OUT          CY_ERU_ETL_INPUT_A0
#define ERU0_ETL0_INPUTA_ACMP2_OUT          CY_ERU_ETL_INPUT_A2
#define ERU0_ETL0_INPUTA_P2_4               CY_ERU_ETL_INPUT_A1
#define ERU0_ETL0_INPUTA_VADC0_G0BFLOUT0    CY_ERU_ETL_INPUT_A3
#define ERU0_ETL0_INPUTB_ACMP0_OUT          CY_ERU_ETL_INPUT_B2
#define ERU0_ETL0_INPUTB_P2_0               CY_ERU_ETL_INPUT_B0
#define ERU0_ETL0_INPUTB_P2_2               CY_ERU_ETL_INPUT_B1
#define ERU0_ETL0_INPUTB_VADC0_G1BFLOUT0    CY_ERU_ETL_INPUT_B3
#define ERU0_ETL1_INPUTA_ACMP1_OUT          CY_ERU_ETL_INPUT_A0
#define ERU0_ETL1_INPUTA_ACMP3_OUT          CY_ERU_ETL_INPUT_A2
#define ERU0_ETL1_INPUTA_P2_5               CY_ERU_ETL_INPUT_A1
#define ERU0_ETL1_INPUTA_VADC0_G0BFLOUT1    CY_ERU_ETL_INPUT_A3
#define ERU0_ETL1_INPUTB_ACMP1_OUT          CY_ERU_ETL_INPUT_B2
#define ERU0_ETL1_INPUTB_P2_1               CY_ERU_ETL_INPUT_B0
#define ERU0_ETL1_INPUTB_P2_3               CY_ERU_ETL_INPUT_B1
#define ERU0_ETL1_INPUTB_VADC0_G1BFLOUT1    CY_ERU_ETL_INPUT_B3
#define ERU0_ETL2_INPUTA_ACMP2_OUT          CY_ERU_ETL_INPUT_A0
#define ERU0_ETL2_INPUTA_ACMP4_OUT          CY_ERU_ETL_INPUT_A2
#define ERU0_ETL2_INPUTA_P2_6               CY_ERU_ETL_INPUT_A1
#define ERU0_ETL2_INPUTA_VADC0_G0BFLOUT2    CY_ERU_ETL_INPUT_A3
#define ERU0_ETL2_INPUTB_ACMP2_OUT          CY_ERU_ETL_INPUT_B2
#define ERU0_ETL2_INPUTB_P2_10              CY_ERU_ETL_INPUT_B0
#define ERU0_ETL2_INPUTB_P2_11              CY_ERU_ETL_INPUT_B1
#define ERU0_ETL2_INPUTB_VADC0_G1BFLOUT2    CY_ERU_ETL_INPUT_B3
#define ERU0_ETL3_INPUTA_ACMP5_OUT          CY_ERU_ETL_INPUT_A2
#define ERU0_ETL3_INPUTA_ACMP7_OUT          CY_ERU_ETL_INPUT_A0
#define ERU0_ETL3_INPUTA_P2_7               CY_ERU_ETL_INPUT_A1
#define ERU0_ETL3_INPUTA_VADC0_G0BFLOUT3    CY_ERU_ETL_INPUT_A3
#define ERU0_ETL3_INPUTB_ACMP6_OUT          CY_ERU_ETL_INPUT_B2
#define ERU0_ETL3_INPUTB_P2_8               CY_ERU_ETL_INPUT_B1
#define ERU0_ETL3_INPUTB_P2_9               CY_ERU_ETL_INPUT_B0
#define ERU0_ETL3_INPUTB_VADC0_G1BFLOUT3    CY_ERU_ETL_INPUT_B3
#define ERU1_ETL0_INPUTA_ACMP1_OUT          CY_ERU_ETL_INPUT_A0
#define ERU1_ETL0_INPUTA_P3_0               CY_ERU_ETL_INPUT_A1
#define ERU1_ETL0_INPUTA_P4_4               CY_ERU_ETL_INPUT_A2
#define ERU1_ETL0_INPUTA_P4_7               CY_ERU_ETL_INPUT_A3
#define ERU1_ETL0_INPUTB_CCU40_ST0          CY_ERU_ETL_INPUT_B0
#define ERU1_ETL0_INPUTB_CCU41_ST0          CY_ERU_ETL_INPUT_B1
#define ERU1_ETL0_INPUTB_CCU80_ST0          CY_ERU_ETL_INPUT_B2
#define ERU1_ETL0_INPUTB_CCU81_ST0          CY_ERU_ETL_INPUT_B3
#define ERU1_ETL1_INPUTA_ACMP3_OUT          CY_ERU_ETL_INPUT_A0
#define ERU1_ETL1_INPUTA_P4_5               CY_ERU_ETL_INPUT_A2
#define ERU1_ETL1_INPUTB_CCU40_ST1          CY_ERU_ETL_INPUT_B0
#define ERU1_ETL1_INPUTB_CCU41_ST1          CY_ERU_ETL_INPUT_B1
#define ERU1_ETL1_INPUTB_CCU80_ST3          CY_ERU_ETL_INPUT_B2
#define ERU1_ETL1_INPUTB_CCU81_ST3          CY_ERU_ETL_INPUT_B3
#define ERU1_ETL2_INPUTA_ACMP2_OUT          CY_ERU_ETL_INPUT_A0
#define ERU1_ETL2_INPUTA_P4_6               CY_ERU_ETL_INPUT_A2
#define ERU1_ETL2_INPUTB_CCU40_ST2          CY_ERU_ETL_INPUT_B0
#define ERU1_ETL2_INPUTB_CCU41_ST2          CY_ERU_ETL_INPUT_B1
#define ERU1_ETL2_INPUTB_CCU80_ST1          CY_ERU_ETL_INPUT_B2
#define ERU1_ETL2_INPUTB_CCU81_ST1          CY_ERU_ETL_INPUT_B3
#define ERU1_ETL3_INPUTA_ACMP0_OUT          CY_ERU_ETL_INPUT_A0
#define ERU1_ETL3_INPUTA_P2_12              CY_ERU_ETL_INPUT_A2
#define ERU1_ETL3_INPUTA_P2_13              CY_ERU_ETL_INPUT_A3
#define ERU1_ETL3_INPUTA_POSIF1_SR1         CY_ERU_ETL_INPUT_A1
#define ERU1_ETL3_INPUTB_CCU40_ST3          CY_ERU_ETL_INPUT_B0
#define ERU1_ETL3_INPUTB_CCU41_ST3          CY_ERU_ETL_INPUT_B1
#define ERU1_ETL3_INPUTB_CCU80_ST2          CY_ERU_ETL_INPUT_B2
#define ERU1_ETL3_INPUTB_CCU81_ST2          CY_ERU_ETL_INPUT_B3

#define ERU0_OGU0_PERIPHERAL_TRIGGER_CCU40_SR0  CY_ERU_OGU_PERIPHERAL_TRIGGER1
#define ERU0_OGU0_PERIPHERAL_TRIGGER_CCU80_SR2  CY_ERU_OGU_PERIPHERAL_TRIGGER3
#define ERU0_OGU0_PERIPHERAL_TRIGGER_VADC_C0SR2 CY_ERU_OGU_PERIPHERAL_TRIGGER2
#define ERU0_OGU1_PERIPHERAL_TRIGGER_CCU40_SR1  CY_ERU_OGU_PERIPHERAL_TRIGGER1
#define ERU0_OGU1_PERIPHERAL_TRIGGER_CCU80_SR2  CY_ERU_OGU_PERIPHERAL_TRIGGER3
#define ERU0_OGU1_PERIPHERAL_TRIGGER_VADC_C0SR2 CY_ERU_OGU_PERIPHERAL_TRIGGER2
#define ERU0_OGU2_PERIPHERAL_TRIGGER_CCU40_SR2  CY_ERU_OGU_PERIPHERAL_TRIGGER1
#define ERU0_OGU2_PERIPHERAL_TRIGGER_CCU80_SR3  CY_ERU_OGU_PERIPHERAL_TRIGGER3
#define ERU0_OGU2_PERIPHERAL_TRIGGER_VADC_C0SR3 CY_ERU_OGU_PERIPHERAL_TRIGGER2
#define ERU0_OGU3_PERIPHERAL_TRIGGER_CCU40_SR3  CY_ERU_OGU_PERIPHERAL_TRIGGER1
#define ERU0_OGU3_PERIPHERAL_TRIGGER_CCU80_SR3  CY_ERU_OGU_PERIPHERAL_TRIGGER3
#define ERU0_OGU3_PERIPHERAL_TRIGGER_VADC_C0SR3 CY_ERU_OGU_PERIPHERAL_TRIGGER2
#define ERU1_OGU0_PERIPHERAL_TRIGGER_CCU41_SR0  CY_ERU_OGU_PERIPHERAL_TRIGGER1
#define ERU1_OGU0_PERIPHERAL_TRIGGER_CCU81_SR2  CY_ERU_OGU_PERIPHERAL_TRIGGER3
#define ERU1_OGU1_PERIPHERAL_TRIGGER_CCU41_SR1  CY_ERU_OGU_PERIPHERAL_TRIGGER1
#define ERU1_OGU1_PERIPHERAL_TRIGGER_CCU81_SR2  CY_ERU_OGU_PERIPHERAL_TRIGGER3
#define ERU1_OGU2_PERIPHERAL_TRIGGER_CCU41_SR2  CY_ERU_OGU_PERIPHERAL_TRIGGER1
#define ERU1_OGU2_PERIPHERAL_TRIGGER_CCU81_SR3  CY_ERU_OGU_PERIPHERAL_TRIGGER3
#define ERU1_OGU3_PERIPHERAL_TRIGGER_CCU41_SR3  CY_ERU_OGU_PERIPHERAL_TRIGGER1
#define ERU1_OGU3_PERIPHERAL_TRIGGER_CCU81_SR3  CY_ERU_OGU_PERIPHERAL_TRIGGER3
#endif


#if (CY_DEVICE_ID == CY_DEVICE_PSC1M2) && (CY_DEVICE_PACKAGE == LQFP48)
#define ERU0_ETL0_INPUTA_ACMP0_OUT          CY_ERU_ETL_INPUT_A0
#define ERU0_ETL0_INPUTA_ACMP2_OUT          CY_ERU_ETL_INPUT_A2
#define ERU0_ETL0_INPUTA_P2_4               CY_ERU_ETL_INPUT_A1
#define ERU0_ETL0_INPUTA_VADC0_G0BFLOUT0    CY_ERU_ETL_INPUT_A3
#define ERU0_ETL0_INPUTB_ACMP0_OUT          CY_ERU_ETL_INPUT_B2
#define ERU0_ETL0_INPUTB_P2_0               CY_ERU_ETL_INPUT_B0
#define ERU0_ETL0_INPUTB_P2_2               CY_ERU_ETL_INPUT_B1
#define ERU0_ETL0_INPUTB_VADC0_G1BFLOUT0    CY_ERU_ETL_INPUT_B3
#define ERU0_ETL1_INPUTA_ACMP1_OUT          CY_ERU_ETL_INPUT_A0
#define ERU0_ETL1_INPUTA_ACMP3_OUT          CY_ERU_ETL_INPUT_A2
#define ERU0_ETL1_INPUTA_P2_5               CY_ERU_ETL_INPUT_A1
#define ERU0_ETL1_INPUTA_VADC0_G0BFLOUT1    CY_ERU_ETL_INPUT_A3
#define ERU0_ETL1_INPUTB_ACMP1_OUT          CY_ERU_ETL_INPUT_B2
#define ERU0_ETL1_INPUTB_P2_1               CY_ERU_ETL_INPUT_B0
#define ERU0_ETL1_INPUTB_P2_3               CY_ERU_ETL_INPUT_B1
#define ERU0_ETL1_INPUTB_VADC0_G1BFLOUT1    CY_ERU_ETL_INPUT_B3
#define ERU0_ETL2_INPUTA_ACMP2_OUT          CY_ERU_ETL_INPUT_A0
#define ERU0_ETL2_INPUTA_ACMP4_OUT          CY_ERU_ETL_INPUT_A2
#define ERU0_ETL2_INPUTA_P2_6               CY_ERU_ETL_INPUT_A1
#define ERU0_ETL2_INPUTA_VADC0_G0BFLOUT2    CY_ERU_ETL_INPUT_A3
#define ERU0_ETL2_INPUTB_ACMP2_OUT          CY_ERU_ETL_INPUT_B2
#define ERU0_ETL2_INPUTB_P2_10              CY_ERU_ETL_INPUT_B0
#define ERU0_ETL2_INPUTB_P2_11              CY_ERU_ETL_INPUT_B1
#define ERU0_ETL2_INPUTB_VADC0_G1BFLOUT2    CY_ERU_ETL_INPUT_B3
#define ERU0_ETL3_INPUTA_ACMP5_OUT          CY_ERU_ETL_INPUT_A2
#define ERU0_ETL3_INPUTA_ACMP7_OUT          CY_ERU_ETL_INPUT_A0
#define ERU0_ETL3_INPUTA_P2_7               CY_ERU_ETL_INPUT_A1
#define ERU0_ETL3_INPUTA_VADC0_G0BFLOUT3    CY_ERU_ETL_INPUT_A3
#define ERU0_ETL3_INPUTB_ACMP6_OUT          CY_ERU_ETL_INPUT_B2
#define ERU0_ETL3_INPUTB_P2_8               CY_ERU_ETL_INPUT_B1
#define ERU0_ETL3_INPUTB_P2_9               CY_ERU_ETL_INPUT_B0
#define ERU0_ETL3_INPUTB_VADC0_G1BFLOUT3    CY_ERU_ETL_INPUT_B3
#define ERU1_ETL0_INPUTA_ACMP1_OUT          CY_ERU_ETL_INPUT_A0
#define ERU1_ETL0_INPUTA_P3_0               CY_ERU_ETL_INPUT_A1
#define ERU1_ETL0_INPUTA_P4_7               CY_ERU_ETL_INPUT_A3
#define ERU1_ETL0_INPUTB_CCU40_ST0          CY_ERU_ETL_INPUT_B0
#define ERU1_ETL0_INPUTB_CCU41_ST0          CY_ERU_ETL_INPUT_B1
#define ERU1_ETL0_INPUTB_CCU80_ST0          CY_ERU_ETL_INPUT_B2
#define ERU1_ETL0_INPUTB_CCU81_ST0          CY_ERU_ETL_INPUT_B3
#define ERU1_ETL1_INPUTA_ACMP3_OUT          CY_ERU_ETL_INPUT_A0

#define ERU1_ETL1_INPUTB_CCU40_ST1          CY_ERU_ETL_INPUT_B0
#define ERU1_ETL1_INPUTB_CCU41_ST1          CY_ERU_ETL_INPUT_B1
#define ERU1_ETL1_INPUTB_CCU80_ST3          CY_ERU_ETL_INPUT_B2
#define ERU1_ETL1_INPUTB_CCU81_ST3          CY_ERU_ETL_INPUT_B3
#define ERU1_ETL2_INPUTA_ACMP2_OUT          CY_ERU_ETL_INPUT_A0
#define ERU1_ETL2_INPUTA_P4_6               CY_ERU_ETL_INPUT_A2
#define ERU1_ETL2_INPUTB_CCU40_ST2          CY_ERU_ETL_INPUT_B0
#define ERU1_ETL2_INPUTB_CCU41_ST2          CY_ERU_ETL_INPUT_B1
#define ERU1_ETL2_INPUTB_CCU80_ST1          CY_ERU_ETL_INPUT_B2
#define ERU1_ETL2_INPUTB_CCU81_ST1          CY_ERU_ETL_INPUT_B3
#define ERU1_ETL3_INPUTA_ACMP0_OUT          CY_ERU_ETL_INPUT_A0
#define ERU1_ETL3_INPUTA_P2_12              CY_ERU_ETL_INPUT_A2
#define ERU1_ETL3_INPUTA_P2_13              CY_ERU_ETL_INPUT_A3
#define ERU1_ETL3_INPUTA_POSIF1_SR1         CY_ERU_ETL_INPUT_A1
#define ERU1_ETL3_INPUTB_CCU40_ST3          CY_ERU_ETL_INPUT_B0
#define ERU1_ETL3_INPUTB_CCU41_ST3          CY_ERU_ETL_INPUT_B1
#define ERU1_ETL3_INPUTB_CCU80_ST2          CY_ERU_ETL_INPUT_B2
#define ERU1_ETL3_INPUTB_CCU81_ST2          CY_ERU_ETL_INPUT_B3

#define ERU0_OGU0_PERIPHERAL_TRIGGER_CCU40_SR0  CY_ERU_OGU_PERIPHERAL_TRIGGER1
#define ERU0_OGU0_PERIPHERAL_TRIGGER_CCU80_SR2  CY_ERU_OGU_PERIPHERAL_TRIGGER3
#define ERU0_OGU0_PERIPHERAL_TRIGGER_VADC_C0SR2 CY_ERU_OGU_PERIPHERAL_TRIGGER2
#define ERU0_OGU1_PERIPHERAL_TRIGGER_CCU40_SR1  CY_ERU_OGU_PERIPHERAL_TRIGGER1
#define ERU0_OGU1_PERIPHERAL_TRIGGER_CCU80_SR2  CY_ERU_OGU_PERIPHERAL_TRIGGER3
#define ERU0_OGU1_PERIPHERAL_TRIGGER_VADC_C0SR2 CY_ERU_OGU_PERIPHERAL_TRIGGER2
#define ERU0_OGU2_PERIPHERAL_TRIGGER_CCU40_SR2  CY_ERU_OGU_PERIPHERAL_TRIGGER1
#define ERU0_OGU2_PERIPHERAL_TRIGGER_CCU80_SR3  CY_ERU_OGU_PERIPHERAL_TRIGGER3
#define ERU0_OGU2_PERIPHERAL_TRIGGER_VADC_C0SR3 CY_ERU_OGU_PERIPHERAL_TRIGGER2
#define ERU0_OGU3_PERIPHERAL_TRIGGER_CCU40_SR3  CY_ERU_OGU_PERIPHERAL_TRIGGER1
#define ERU0_OGU3_PERIPHERAL_TRIGGER_CCU80_SR3  CY_ERU_OGU_PERIPHERAL_TRIGGER3
#define ERU0_OGU3_PERIPHERAL_TRIGGER_VADC_C0SR3 CY_ERU_OGU_PERIPHERAL_TRIGGER2
#define ERU1_OGU0_PERIPHERAL_TRIGGER_CCU41_SR0  CY_ERU_OGU_PERIPHERAL_TRIGGER1
#define ERU1_OGU0_PERIPHERAL_TRIGGER_CCU81_SR2  CY_ERU_OGU_PERIPHERAL_TRIGGER3
#define ERU1_OGU1_PERIPHERAL_TRIGGER_CCU41_SR1  CY_ERU_OGU_PERIPHERAL_TRIGGER1
#define ERU1_OGU1_PERIPHERAL_TRIGGER_CCU81_SR2  CY_ERU_OGU_PERIPHERAL_TRIGGER3
#define ERU1_OGU2_PERIPHERAL_TRIGGER_CCU41_SR2  CY_ERU_OGU_PERIPHERAL_TRIGGER1
#define ERU1_OGU2_PERIPHERAL_TRIGGER_CCU81_SR3  CY_ERU_OGU_PERIPHERAL_TRIGGER3
#define ERU1_OGU3_PERIPHERAL_TRIGGER_CCU41_SR3  CY_ERU_OGU_PERIPHERAL_TRIGGER1
#define ERU1_OGU3_PERIPHERAL_TRIGGER_CCU81_SR3  CY_ERU_OGU_PERIPHERAL_TRIGGER3
#endif



#if (CY_DEVICE_ID == CY_DEVICE_PSC1M2) && (CY_DEVICE_PACKAGE == TSSOP38)
#define ERU0_ETL0_INPUTA_ACMP0_OUT          CY_ERU_ETL_INPUT_A0
#define ERU0_ETL0_INPUTA_ACMP2_OUT          CY_ERU_ETL_INPUT_A2
#define ERU0_ETL0_INPUTA_P2_4               CY_ERU_ETL_INPUT_A1
#define ERU0_ETL0_INPUTA_VADC0_G0BFLOUT0    CY_ERU_ETL_INPUT_A3
#define ERU0_ETL0_INPUTB_ACMP0_OUT          CY_ERU_ETL_INPUT_B2
#define ERU0_ETL0_INPUTB_P2_0               CY_ERU_ETL_INPUT_B0
#define ERU0_ETL0_INPUTB_P2_2               CY_ERU_ETL_INPUT_B1
#define ERU0_ETL0_INPUTB_VADC0_G1BFLOUT0    CY_ERU_ETL_INPUT_B3
#define ERU0_ETL1_INPUTA_ACMP1_OUT          CY_ERU_ETL_INPUT_A0
#define ERU0_ETL1_INPUTA_ACMP3_OUT          CY_ERU_ETL_INPUT_A2
#define ERU0_ETL1_INPUTA_P2_5               CY_ERU_ETL_INPUT_A1
#define ERU0_ETL1_INPUTA_VADC0_G0BFLOUT1    CY_ERU_ETL_INPUT_A3
#define ERU0_ETL1_INPUTB_ACMP1_OUT          CY_ERU_ETL_INPUT_B2
#define ERU0_ETL1_INPUTB_P2_1               CY_ERU_ETL_INPUT_B0
#define ERU0_ETL1_INPUTB_P2_3               CY_ERU_ETL_INPUT_B1
#define ERU0_ETL1_INPUTB_VADC0_G1BFLOUT1    CY_ERU_ETL_INPUT_B3
#define ERU0_ETL2_INPUTA_ACMP2_OUT          CY_ERU_ETL_INPUT_A0
#define ERU0_ETL2_INPUTA_ACMP4_OUT          CY_ERU_ETL_INPUT_A2
#define ERU0_ETL2_INPUTA_P2_6               CY_ERU_ETL_INPUT_A1
#define ERU0_ETL2_INPUTA_VADC0_G0BFLOUT2    CY_ERU_ETL_INPUT_A3
#define ERU0_ETL2_INPUTB_ACMP2_OUT          CY_ERU_ETL_INPUT_B2
#define ERU0_ETL2_INPUTB_P2_10              CY_ERU_ETL_INPUT_B0
#define ERU0_ETL2_INPUTB_P2_11              CY_ERU_ETL_INPUT_B1
#define ERU0_ETL2_INPUTB_VADC0_G1BFLOUT2    CY_ERU_ETL_INPUT_B3
#define ERU0_ETL3_INPUTA_ACMP5_OUT          CY_ERU_ETL_INPUT_A2
#define ERU0_ETL3_INPUTA_ACMP7_OUT          CY_ERU_ETL_INPUT_A0
#define ERU0_ETL3_INPUTA_P2_7               CY_ERU_ETL_INPUT_A1
#define ERU0_ETL3_INPUTA_VADC0_G0BFLOUT3    CY_ERU_ETL_INPUT_A3
#define ERU0_ETL3_INPUTB_ACMP6_OUT          CY_ERU_ETL_INPUT_B2
#define ERU0_ETL3_INPUTB_P2_8               CY_ERU_ETL_INPUT_B1
#define ERU0_ETL3_INPUTB_P2_9               CY_ERU_ETL_INPUT_B0
#define ERU0_ETL3_INPUTB_VADC0_G1BFLOUT3    CY_ERU_ETL_INPUT_B3
#define ERU1_ETL0_INPUTA_ACMP1_OUT          CY_ERU_ETL_INPUT_A0
#define ERU1_ETL0_INPUTB_CCU40_ST0          CY_ERU_ETL_INPUT_B0
#define ERU1_ETL0_INPUTB_CCU41_ST0          CY_ERU_ETL_INPUT_B1
#define ERU1_ETL0_INPUTB_CCU80_ST0          CY_ERU_ETL_INPUT_B2
#define ERU1_ETL0_INPUTB_CCU81_ST0          CY_ERU_ETL_INPUT_B3
#define ERU1_ETL1_INPUTB_CCU40_ST1          CY_ERU_ETL_INPUT_B0
#define ERU1_ETL1_INPUTB_CCU41_ST1          CY_ERU_ETL_INPUT_B1
#define ERU1_ETL1_INPUTB_CCU80_ST3          CY_ERU_ETL_INPUT_B2
#define ERU1_ETL1_INPUTB_CCU81_ST3          CY_ERU_ETL_INPUT_B3
#define ERU1_ETL2_INPUTA_ACMP2_OUT          CY_ERU_ETL_INPUT_A0
#define ERU1_ETL2_INPUTB_CCU40_ST2          CY_ERU_ETL_INPUT_B0
#define ERU1_ETL2_INPUTB_CCU41_ST2          CY_ERU_ETL_INPUT_B1
#define ERU1_ETL2_INPUTB_CCU80_ST1          CY_ERU_ETL_INPUT_B2
#define ERU1_ETL2_INPUTB_CCU81_ST1          CY_ERU_ETL_INPUT_B3
#define ERU1_ETL3_INPUTA_ACMP0_OUT          CY_ERU_ETL_INPUT_A0
#define ERU1_ETL3_INPUTB_CCU40_ST3          CY_ERU_ETL_INPUT_B0
#define ERU1_ETL3_INPUTB_CCU41_ST3          CY_ERU_ETL_INPUT_B1
#define ERU1_ETL3_INPUTB_CCU80_ST2          CY_ERU_ETL_INPUT_B2
#define ERU1_ETL3_INPUTB_CCU81_ST2          CY_ERU_ETL_INPUT_B3

#define ERU0_OGU0_PERIPHERAL_TRIGGER_CCU40_SR0  CY_ERU_OGU_PERIPHERAL_TRIGGER1
#define ERU0_OGU0_PERIPHERAL_TRIGGER_CCU80_SR2  CY_ERU_OGU_PERIPHERAL_TRIGGER3
#define ERU0_OGU0_PERIPHERAL_TRIGGER_VADC_C0SR2 CY_ERU_OGU_PERIPHERAL_TRIGGER2
#define ERU0_OGU1_PERIPHERAL_TRIGGER_CCU40_SR1  CY_ERU_OGU_PERIPHERAL_TRIGGER1
#define ERU0_OGU1_PERIPHERAL_TRIGGER_CCU80_SR2  CY_ERU_OGU_PERIPHERAL_TRIGGER3
#define ERU0_OGU1_PERIPHERAL_TRIGGER_VADC_C0SR2 CY_ERU_OGU_PERIPHERAL_TRIGGER2
#define ERU0_OGU2_PERIPHERAL_TRIGGER_CCU40_SR2  CY_ERU_OGU_PERIPHERAL_TRIGGER1
#define ERU0_OGU2_PERIPHERAL_TRIGGER_CCU80_SR3  CY_ERU_OGU_PERIPHERAL_TRIGGER3
#define ERU0_OGU2_PERIPHERAL_TRIGGER_VADC_C0SR3 CY_ERU_OGU_PERIPHERAL_TRIGGER2
#define ERU0_OGU3_PERIPHERAL_TRIGGER_CCU40_SR3  CY_ERU_OGU_PERIPHERAL_TRIGGER1
#define ERU0_OGU3_PERIPHERAL_TRIGGER_CCU80_SR3  CY_ERU_OGU_PERIPHERAL_TRIGGER3
#define ERU0_OGU3_PERIPHERAL_TRIGGER_VADC_C0SR3 CY_ERU_OGU_PERIPHERAL_TRIGGER2
#define ERU1_OGU0_PERIPHERAL_TRIGGER_CCU41_SR0  CY_ERU_OGU_PERIPHERAL_TRIGGER1
#define ERU1_OGU0_PERIPHERAL_TRIGGER_CCU81_SR2  CY_ERU_OGU_PERIPHERAL_TRIGGER3
#define ERU1_OGU1_PERIPHERAL_TRIGGER_CCU41_SR1  CY_ERU_OGU_PERIPHERAL_TRIGGER1
#define ERU1_OGU1_PERIPHERAL_TRIGGER_CCU81_SR2  CY_ERU_OGU_PERIPHERAL_TRIGGER3
#define ERU1_OGU2_PERIPHERAL_TRIGGER_CCU41_SR2  CY_ERU_OGU_PERIPHERAL_TRIGGER1
#define ERU1_OGU2_PERIPHERAL_TRIGGER_CCU81_SR3  CY_ERU_OGU_PERIPHERAL_TRIGGER3
#define ERU1_OGU3_PERIPHERAL_TRIGGER_CCU41_SR3  CY_ERU_OGU_PERIPHERAL_TRIGGER1
#define ERU1_OGU3_PERIPHERAL_TRIGGER_CCU81_SR3  CY_ERU_OGU_PERIPHERAL_TRIGGER3
#endif

#if (CY_DEVICE_ID == CY_DEVICE_PSC1M3) && (CY_DEVICE_PACKAGE == VQFN48)
#define ERU0_ETL0_INPUTA_ACMP0_OUT          CY_ERU_ETL_INPUT_A0
#define ERU0_ETL0_INPUTA_ACMP2_OUT          CY_ERU_ETL_INPUT_A2
#define ERU0_ETL0_INPUTA_P2_4               CY_ERU_ETL_INPUT_A1
#define ERU0_ETL0_INPUTA_VADC0_G0BFLOUT0    CY_ERU_ETL_INPUT_A3
#define ERU0_ETL0_INPUTB_ACMP0_OUT          CY_ERU_ETL_INPUT_B2
#define ERU0_ETL0_INPUTB_P2_0               CY_ERU_ETL_INPUT_B0
#define ERU0_ETL0_INPUTB_P2_2               CY_ERU_ETL_INPUT_B1
#define ERU0_ETL0_INPUTB_VADC0_G1BFLOUT0    CY_ERU_ETL_INPUT_B3
#define ERU0_ETL1_INPUTA_ACMP1_OUT          CY_ERU_ETL_INPUT_A0
#define ERU0_ETL1_INPUTA_ACMP3_OUT          CY_ERU_ETL_INPUT_A2
#define ERU0_ETL1_INPUTA_P2_5               CY_ERU_ETL_INPUT_A1
#define ERU0_ETL1_INPUTA_VADC0_G0BFLOUT1    CY_ERU_ETL_INPUT_A3
#define ERU0_ETL1_INPUTB_ACMP1_OUT          CY_ERU_ETL_INPUT_B2
#define ERU0_ETL1_INPUTB_P2_1               CY_ERU_ETL_INPUT_B0
#define ERU0_ETL1_INPUTB_P2_3               CY_ERU_ETL_INPUT_B1
#define ERU0_ETL1_INPUTB_VADC0_G1BFLOUT1    CY_ERU_ETL_INPUT_B3
#define ERU0_ETL2_INPUTA_ACMP2_OUT          CY_ERU_ETL_INPUT_A0
#define ERU0_ETL2_INPUTA_ACMP4_OUT          CY_ERU_ETL_INPUT_A2
#define ERU0_ETL2_INPUTA_P2_6               CY_ERU_ETL_INPUT_A1
#define ERU0_ETL2_INPUTA_VADC0_G0BFLOUT2    CY_ERU_ETL_INPUT_A3
#define ERU0_ETL2_INPUTB_ACMP2_OUT          CY_ERU_ETL_INPUT_B2
#define ERU0_ETL2_INPUTB_P2_10              CY_ERU_ETL_INPUT_B0
#define ERU0_ETL2_INPUTB_P2_11              CY_ERU_ETL_INPUT_B1
#define ERU0_ETL2_INPUTB_VADC0_G1BFLOUT2    CY_ERU_ETL_INPUT_B3
#define ERU0_ETL3_INPUTA_ACMP5_OUT          CY_ERU_ETL_INPUT_A2
#define ERU0_ETL3_INPUTA_ACMP7_OUT          CY_ERU_ETL_INPUT_A0
#define ERU0_ETL3_INPUTA_P2_7               CY_ERU_ETL_INPUT_A1
#define ERU0_ETL3_INPUTA_VADC0_G0BFLOUT3    CY_ERU_ETL_INPUT_A3
#define ERU0_ETL3_INPUTB_ACMP6_OUT          CY_ERU_ETL_INPUT_B2
#define ERU0_ETL3_INPUTB_P2_8               CY_ERU_ETL_INPUT_B1
#define ERU0_ETL3_INPUTB_P2_9               CY_ERU_ETL_INPUT_B0
#define ERU0_ETL3_INPUTB_VADC0_G1BFLOUT3    CY_ERU_ETL_INPUT_B3
#define ERU1_ETL0_INPUTA_ACMP1_OUT          CY_ERU_ETL_INPUT_A0
#define ERU1_ETL0_INPUTA_P3_0               CY_ERU_ETL_INPUT_A1
#define ERU1_ETL0_INPUTA_P4_4               CY_ERU_ETL_INPUT_A2
#define ERU1_ETL0_INPUTA_P4_7               CY_ERU_ETL_INPUT_A3
#define ERU1_ETL0_INPUTB_CCU40_ST0          CY_ERU_ETL_INPUT_B0
#define ERU1_ETL0_INPUTB_CCU41_ST0          CY_ERU_ETL_INPUT_B1
#define ERU1_ETL0_INPUTB_CCU80_ST0          CY_ERU_ETL_INPUT_B2
#define ERU1_ETL0_INPUTB_CCU81_ST0          CY_ERU_ETL_INPUT_B3
#define ERU1_ETL1_INPUTA_ACMP3_OUT          CY_ERU_ETL_INPUT_A0
#define ERU1_ETL1_INPUTA_P4_5               CY_ERU_ETL_INPUT_A2
#define ERU1_ETL1_INPUTB_CCU40_ST1          CY_ERU_ETL_INPUT_B0
#define ERU1_ETL1_INPUTB_CCU41_ST1          CY_ERU_ETL_INPUT_B1
#define ERU1_ETL1_INPUTB_CCU80_ST3          CY_ERU_ETL_INPUT_B2
#define ERU1_ETL1_INPUTB_CCU81_ST3          CY_ERU_ETL_INPUT_B3
#define ERU1_ETL2_INPUTA_ACMP2_OUT          CY_ERU_ETL_INPUT_A0
#define ERU1_ETL2_INPUTA_P4_6               CY_ERU_ETL_INPUT_A2
#define ERU1_ETL2_INPUTB_CCU40_ST2          CY_ERU_ETL_INPUT_B0
#define ERU1_ETL2_INPUTB_CCU41_ST2          CY_ERU_ETL_INPUT_B1
#define ERU1_ETL2_INPUTB_CCU80_ST1          CY_ERU_ETL_INPUT_B2
#define ERU1_ETL2_INPUTB_CCU81_ST1          CY_ERU_ETL_INPUT_B3
#define ERU1_ETL3_INPUTA_ACMP0_OUT          CY_ERU_ETL_INPUT_A0
#define ERU1_ETL3_INPUTA_P2_12              CY_ERU_ETL_INPUT_A2
#define ERU1_ETL3_INPUTA_P2_13              CY_ERU_ETL_INPUT_A3
#define ERU1_ETL3_INPUTA_POSIF1_SR1         CY_ERU_ETL_INPUT_A1
#define ERU1_ETL3_INPUTB_CCU40_ST3          CY_ERU_ETL_INPUT_B0
#define ERU1_ETL3_INPUTB_CCU41_ST3          CY_ERU_ETL_INPUT_B1
#define ERU1_ETL3_INPUTB_CCU80_ST2          CY_ERU_ETL_INPUT_B2
#define ERU1_ETL3_INPUTB_CCU81_ST2          CY_ERU_ETL_INPUT_B3

#define ERU0_OGU0_PERIPHERAL_TRIGGER_CCU40_SR0  CY_ERU_OGU_PERIPHERAL_TRIGGER1
#define ERU0_OGU0_PERIPHERAL_TRIGGER_CCU80_SR2  CY_ERU_OGU_PERIPHERAL_TRIGGER3
#define ERU0_OGU0_PERIPHERAL_TRIGGER_VADC_C0SR2 CY_ERU_OGU_PERIPHERAL_TRIGGER2
#define ERU0_OGU1_PERIPHERAL_TRIGGER_CCU40_SR1  CY_ERU_OGU_PERIPHERAL_TRIGGER1
#define ERU0_OGU1_PERIPHERAL_TRIGGER_CCU80_SR2  CY_ERU_OGU_PERIPHERAL_TRIGGER3
#define ERU0_OGU1_PERIPHERAL_TRIGGER_VADC_C0SR2 CY_ERU_OGU_PERIPHERAL_TRIGGER2
#define ERU0_OGU2_PERIPHERAL_TRIGGER_CCU40_SR2  CY_ERU_OGU_PERIPHERAL_TRIGGER1
#define ERU0_OGU2_PERIPHERAL_TRIGGER_CCU80_SR3  CY_ERU_OGU_PERIPHERAL_TRIGGER3
#define ERU0_OGU2_PERIPHERAL_TRIGGER_VADC_C0SR3 CY_ERU_OGU_PERIPHERAL_TRIGGER2
#define ERU0_OGU3_PERIPHERAL_TRIGGER_CCU40_SR3  CY_ERU_OGU_PERIPHERAL_TRIGGER1
#define ERU0_OGU3_PERIPHERAL_TRIGGER_CCU80_SR3  CY_ERU_OGU_PERIPHERAL_TRIGGER3
#define ERU0_OGU3_PERIPHERAL_TRIGGER_VADC_C0SR3 CY_ERU_OGU_PERIPHERAL_TRIGGER2
#define ERU1_OGU0_PERIPHERAL_TRIGGER_CAN0_SR4 CY_ERU_OGU_PERIPHERAL_TRIGGER2
#define ERU1_OGU0_PERIPHERAL_TRIGGER_CCU41_SR0  CY_ERU_OGU_PERIPHERAL_TRIGGER1
#define ERU1_OGU0_PERIPHERAL_TRIGGER_CCU81_SR2  CY_ERU_OGU_PERIPHERAL_TRIGGER3
#define ERU1_OGU1_PERIPHERAL_TRIGGER_CAN0_SR5 CY_ERU_OGU_PERIPHERAL_TRIGGER2
#define ERU1_OGU1_PERIPHERAL_TRIGGER_CCU41_SR1  CY_ERU_OGU_PERIPHERAL_TRIGGER1
#define ERU1_OGU1_PERIPHERAL_TRIGGER_CCU81_SR2  CY_ERU_OGU_PERIPHERAL_TRIGGER3
#define ERU1_OGU2_PERIPHERAL_TRIGGER_CAN0_SR6 CY_ERU_OGU_PERIPHERAL_TRIGGER2
#define ERU1_OGU2_PERIPHERAL_TRIGGER_CCU41_SR2  CY_ERU_OGU_PERIPHERAL_TRIGGER1
#define ERU1_OGU2_PERIPHERAL_TRIGGER_CCU81_SR3  CY_ERU_OGU_PERIPHERAL_TRIGGER3
#define ERU1_OGU3_PERIPHERAL_TRIGGER_CAN0_SR7 CY_ERU_OGU_PERIPHERAL_TRIGGER2
#define ERU1_OGU3_PERIPHERAL_TRIGGER_CCU41_SR3  CY_ERU_OGU_PERIPHERAL_TRIGGER1
#define ERU1_OGU3_PERIPHERAL_TRIGGER_CCU81_SR3  CY_ERU_OGU_PERIPHERAL_TRIGGER3
#endif


#if (CY_DEVICE_ID == CY_DEVICE_PSC1M3) && (CY_DEVICE_PACKAGE == LQFP48)
#define ERU0_ETL0_INPUTA_ACMP0_OUT          CY_ERU_ETL_INPUT_A0
#define ERU0_ETL0_INPUTA_ACMP2_OUT          CY_ERU_ETL_INPUT_A2
#define ERU0_ETL0_INPUTA_P2_4               CY_ERU_ETL_INPUT_A1
#define ERU0_ETL0_INPUTA_VADC0_G0BFLOUT0    CY_ERU_ETL_INPUT_A3
#define ERU0_ETL0_INPUTB_ACMP0_OUT          CY_ERU_ETL_INPUT_B2
#define ERU0_ETL0_INPUTB_P2_0               CY_ERU_ETL_INPUT_B0
#define ERU0_ETL0_INPUTB_P2_2               CY_ERU_ETL_INPUT_B1
#define ERU0_ETL0_INPUTB_VADC0_G1BFLOUT0    CY_ERU_ETL_INPUT_B3
#define ERU0_ETL1_INPUTA_ACMP1_OUT          CY_ERU_ETL_INPUT_A0
#define ERU0_ETL1_INPUTA_ACMP3_OUT          CY_ERU_ETL_INPUT_A2
#define ERU0_ETL1_INPUTA_P2_5               CY_ERU_ETL_INPUT_A1
#define ERU0_ETL1_INPUTA_VADC0_G0BFLOUT1    CY_ERU_ETL_INPUT_A3
#define ERU0_ETL1_INPUTB_ACMP1_OUT          CY_ERU_ETL_INPUT_B2
#define ERU0_ETL1_INPUTB_P2_1               CY_ERU_ETL_INPUT_B0
#define ERU0_ETL1_INPUTB_P2_3               CY_ERU_ETL_INPUT_B1
#define ERU0_ETL1_INPUTB_VADC0_G1BFLOUT1    CY_ERU_ETL_INPUT_B3
#define ERU0_ETL2_INPUTA_ACMP2_OUT          CY_ERU_ETL_INPUT_A0
#define ERU0_ETL2_INPUTA_ACMP4_OUT          CY_ERU_ETL_INPUT_A2
#define ERU0_ETL2_INPUTA_P2_6               CY_ERU_ETL_INPUT_A1
#define ERU0_ETL2_INPUTA_VADC0_G0BFLOUT2    CY_ERU_ETL_INPUT_A3
#define ERU0_ETL2_INPUTB_ACMP2_OUT          CY_ERU_ETL_INPUT_B2
#define ERU0_ETL2_INPUTB_P2_10              CY_ERU_ETL_INPUT_B0
#define ERU0_ETL2_INPUTB_P2_11              CY_ERU_ETL_INPUT_B1
#define ERU0_ETL2_INPUTB_VADC0_G1BFLOUT2    CY_ERU_ETL_INPUT_B3
#define ERU0_ETL3_INPUTA_ACMP5_OUT          CY_ERU_ETL_INPUT_A2
#define ERU0_ETL3_INPUTA_ACMP7_OUT          CY_ERU_ETL_INPUT_A0
#define ERU0_ETL3_INPUTA_P2_7               CY_ERU_ETL_INPUT_A1
#define ERU0_ETL3_INPUTA_VADC0_G0BFLOUT3    CY_ERU_ETL_INPUT_A3
#define ERU0_ETL3_INPUTB_ACMP6_OUT          CY_ERU_ETL_INPUT_B2
#define ERU0_ETL3_INPUTB_P2_8               CY_ERU_ETL_INPUT_B1
#define ERU0_ETL3_INPUTB_P2_9               CY_ERU_ETL_INPUT_B0
#define ERU0_ETL3_INPUTB_VADC0_G1BFLOUT3    CY_ERU_ETL_INPUT_B3
#define ERU1_ETL0_INPUTA_ACMP1_OUT          CY_ERU_ETL_INPUT_A0
#define ERU1_ETL0_INPUTA_P3_0               CY_ERU_ETL_INPUT_A1
#define ERU1_ETL0_INPUTA_P4_7               CY_ERU_ETL_INPUT_A3
#define ERU1_ETL0_INPUTB_CCU40_ST0          CY_ERU_ETL_INPUT_B0
#define ERU1_ETL0_INPUTB_CCU41_ST0          CY_ERU_ETL_INPUT_B1
#define ERU1_ETL0_INPUTB_CCU80_ST0          CY_ERU_ETL_INPUT_B2
#define ERU1_ETL0_INPUTB_CCU81_ST0          CY_ERU_ETL_INPUT_B3
#define ERU1_ETL1_INPUTA_ACMP3_OUT          CY_ERU_ETL_INPUT_A0
#define ERU1_ETL1_INPUTB_CCU40_ST1          CY_ERU_ETL_INPUT_B0
#define ERU1_ETL1_INPUTB_CCU41_ST1          CY_ERU_ETL_INPUT_B1
#define ERU1_ETL1_INPUTB_CCU80_ST3          CY_ERU_ETL_INPUT_B2
#define ERU1_ETL1_INPUTB_CCU81_ST3          CY_ERU_ETL_INPUT_B3
#define ERU1_ETL2_INPUTA_ACMP2_OUT          CY_ERU_ETL_INPUT_A0
#define ERU1_ETL2_INPUTA_P4_6               CY_ERU_ETL_INPUT_A2
#define ERU1_ETL2_INPUTB_CCU40_ST2          CY_ERU_ETL_INPUT_B0
#define ERU1_ETL2_INPUTB_CCU41_ST2          CY_ERU_ETL_INPUT_B1
#define ERU1_ETL2_INPUTB_CCU80_ST1          CY_ERU_ETL_INPUT_B2
#define ERU1_ETL2_INPUTB_CCU81_ST1          CY_ERU_ETL_INPUT_B3
#define ERU1_ETL3_INPUTA_ACMP0_OUT          CY_ERU_ETL_INPUT_A0
#define ERU1_ETL3_INPUTA_P2_12              CY_ERU_ETL_INPUT_A2
#define ERU1_ETL3_INPUTA_P2_13              CY_ERU_ETL_INPUT_A3
#define ERU1_ETL3_INPUTA_POSIF1_SR1         CY_ERU_ETL_INPUT_A1
#define ERU1_ETL3_INPUTB_CCU40_ST3          CY_ERU_ETL_INPUT_B0
#define ERU1_ETL3_INPUTB_CCU41_ST3          CY_ERU_ETL_INPUT_B1
#define ERU1_ETL3_INPUTB_CCU80_ST2          CY_ERU_ETL_INPUT_B2
#define ERU1_ETL3_INPUTB_CCU81_ST2          CY_ERU_ETL_INPUT_B3

#define ERU0_OGU0_PERIPHERAL_TRIGGER_CCU40_SR0  CY_ERU_OGU_PERIPHERAL_TRIGGER1
#define ERU0_OGU0_PERIPHERAL_TRIGGER_CCU80_SR2  CY_ERU_OGU_PERIPHERAL_TRIGGER3
#define ERU0_OGU0_PERIPHERAL_TRIGGER_VADC_C0SR2 CY_ERU_OGU_PERIPHERAL_TRIGGER2
#define ERU0_OGU1_PERIPHERAL_TRIGGER_CCU40_SR1  CY_ERU_OGU_PERIPHERAL_TRIGGER1
#define ERU0_OGU1_PERIPHERAL_TRIGGER_CCU80_SR2  CY_ERU_OGU_PERIPHERAL_TRIGGER3
#define ERU0_OGU1_PERIPHERAL_TRIGGER_VADC_C0SR2 CY_ERU_OGU_PERIPHERAL_TRIGGER2
#define ERU0_OGU2_PERIPHERAL_TRIGGER_CCU40_SR2  CY_ERU_OGU_PERIPHERAL_TRIGGER1
#define ERU0_OGU2_PERIPHERAL_TRIGGER_CCU80_SR3  CY_ERU_OGU_PERIPHERAL_TRIGGER3
#define ERU0_OGU2_PERIPHERAL_TRIGGER_VADC_C0SR3 CY_ERU_OGU_PERIPHERAL_TRIGGER2
#define ERU0_OGU3_PERIPHERAL_TRIGGER_CCU40_SR3  CY_ERU_OGU_PERIPHERAL_TRIGGER1
#define ERU0_OGU3_PERIPHERAL_TRIGGER_CCU80_SR3  CY_ERU_OGU_PERIPHERAL_TRIGGER3
#define ERU0_OGU3_PERIPHERAL_TRIGGER_VADC_C0SR3 CY_ERU_OGU_PERIPHERAL_TRIGGER2
#define ERU1_OGU0_PERIPHERAL_TRIGGER_CAN0_SR4 CY_ERU_OGU_PERIPHERAL_TRIGGER2
#define ERU1_OGU0_PERIPHERAL_TRIGGER_CCU41_SR0  CY_ERU_OGU_PERIPHERAL_TRIGGER1
#define ERU1_OGU0_PERIPHERAL_TRIGGER_CCU81_SR2  CY_ERU_OGU_PERIPHERAL_TRIGGER3
#define ERU1_OGU1_PERIPHERAL_TRIGGER_CAN0_SR5 CY_ERU_OGU_PERIPHERAL_TRIGGER2
#define ERU1_OGU1_PERIPHERAL_TRIGGER_CCU41_SR1  CY_ERU_OGU_PERIPHERAL_TRIGGER1
#define ERU1_OGU1_PERIPHERAL_TRIGGER_CCU81_SR2  CY_ERU_OGU_PERIPHERAL_TRIGGER3
#define ERU1_OGU2_PERIPHERAL_TRIGGER_CAN0_SR6 CY_ERU_OGU_PERIPHERAL_TRIGGER2
#define ERU1_OGU2_PERIPHERAL_TRIGGER_CCU41_SR2  CY_ERU_OGU_PERIPHERAL_TRIGGER1
#define ERU1_OGU2_PERIPHERAL_TRIGGER_CCU81_SR3  CY_ERU_OGU_PERIPHERAL_TRIGGER3
#define ERU1_OGU3_PERIPHERAL_TRIGGER_CAN0_SR7 CY_ERU_OGU_PERIPHERAL_TRIGGER2
#define ERU1_OGU3_PERIPHERAL_TRIGGER_CCU41_SR3  CY_ERU_OGU_PERIPHERAL_TRIGGER1
#define ERU1_OGU3_PERIPHERAL_TRIGGER_CCU81_SR3  CY_ERU_OGU_PERIPHERAL_TRIGGER3
#endif


#endif /* CY_ERU_MAP_H */
